## Example Usage

This notebook provides a step-by-step guide on how to use the ProvSense application. You'll find practical examples demonstrating its key features, helping you integrate and leverage ProvSense effectively in your workflow.

In [2]:
!python -m venv provsensetest

In [3]:
!source provsensetest/bin/activate

In [4]:
import sys
import pandas as pd
sys.executable

'/opt/anaconda3/bin/python'

In [5]:
!pip install --upgrade ProvSense

Requirement already satisfied: ProvSense in /opt/anaconda3/lib/python3.11/site-packages (1.0.2)
Requirement already satisfied: click<9.0.0,>=8.1.7 in /opt/anaconda3/lib/python3.11/site-packages (from ProvSense) (8.1.7)
Requirement already satisfied: rdflib<8.0.0,>=7.1.3 in /opt/anaconda3/lib/python3.11/site-packages (from ProvSense) (7.1.3)
Requirement already satisfied: sparqlwrapper<3.0.0,>=2.0.0 in /opt/anaconda3/lib/python3.11/site-packages (from ProvSense) (2.0.0)
Requirement already satisfied: pyparsing<4,>=2.1.0 in /opt/anaconda3/lib/python3.11/site-packages (from rdflib<8.0.0,>=7.1.3->ProvSense) (3.1.1)

## CLI-Usage

In [6]:
!provsense-cli

Usage: provsense-cli [OPTIONS] COMMAND [ARGS]...

  CLI commands for the ProvSense

Options:
  --help  Show this message and exit.

Commands:
  compare  Compare changes in knowledge graph files (JSON-LD, Turtle)...

### Compare Options

In [7]:
!provsense-cli -- compare --help

Usage: provsense-cli compare [OPTIONS]

  Compare changes in knowledge graph files (JSON-LD, Turtle) across different
  input sources.

  This function detects and analyzes differences between RDF data sources,
  supporting comparisons at the folder, file, or direct string level.

  Options:

  - --source (str):         The first input source, which can be a folder
  path, file path, or RDF string.         If providing a string, ensure it is
  correctly formatted in JSON-LD or Turtle.

  - --destination (str):         The second input source, which can be a
  folder path, file path, or RDF string.         If providing a string, ensure
  it is correctly formatted in JSON-LD or Turtle.

  Returns:     dict: A dictionary containing the comparison results
  highlighting the differences.

  Raises:     FileNotFoundError: If the specified folder or file does not
  exist.     ValueError: If an unsupported input type is provided.

  Example Usage:   - Compare two folders:

     `$ cli compare --source "folder1" --destination "folder2"`

    - Compare two files:

      `$ cli compare --source "file1.ttl" --destination "file2.ttl"`

    - Compare two RDF strings:

      `$ cli compare --source '{"@context": "http://schema.org", "name":
      "Alice"}' --destination '{"@context": "http://schema.org", "name":
      "Bob"}'`

Options:
  --source TEXT       Source path (file/folder) or string (e.g., JSON-LD/TTL)
                      for comparison. If providing a string, ensure it is
                      properly formatted.  [required]
  --destination TEXT  Destination path (file/folder) or string (e.g., JSON-
                      LD/TTL) for comparison. If providing a string, ensure it
                      is properly formatted.  [required]
  --help              Show this message and exit.

### KGs string comparison

In [8]:
!provsense-cli -- compare --source '{ "@context": { "ex": "http://example.org/" }, "@id": "ex:Person1", "@type": "ex:Person", "ex:name": "Alice" }' --destination '{ "@context": { "ex": "http://example.org/" }, "@id": "ex:Person1", "@type": "ex:Person", "ex:name": "Alice1" }'

2025-02-07 16:14:26,606 - INFO - Comparing strings: { "@context": { "ex": "http://example.org/" }, "@id": "ex:Person1", "@type": "ex:Person", "ex:name": "Alice" } with { "@context": { "ex": "http://example.org/" }, "@id": "ex:Person1", "@type": "ex:Person", "ex:name": "Alice1" }.
2025-02-07 16:14:26,606 - INFO - Checking the input types, i.e, whether it is ttl, json-ld or nt
2025-02-07 16:14:26,612 - INFO - Checking the input types, i.e, whether it is ttl, json-ld or nt
[{'subject': 'http://example.org/Person1', 'property': 'http://example.org/name', 'src_value': 'Alice', 'dst_value': 'Alice1'}]
Comparing { "@context": { "ex": "http://example.org/" }, "@id": "ex:Person1", "@type": "ex:Person", "ex:name": "Alice" } with { "@context": { "ex": "http://example.org/" }, "@id": "ex:Person1", "@type": "ex:Person", "ex:name": "Alice1" }.

### File comparison

In [9]:
!provsense-cli -- compare --source test_src.jsonld --destination test_dst.jsonld

2025-02-07 16:14:26,864 - INFO - Comparing files: test_src.jsonld with test_dst.jsonld.
2025-02-07 16:14:26,864 - INFO - Checking the input types, i.e, whether it is ttl, json-ld or nt
2025-02-07 16:14:26,869 - INFO - Checking the input types, i.e, whether it is ttl, json-ld or nt
[{'subject': 'urn:uuid:550e8400-e29b-41d4-a716-446655440000', 'property': 'http://example.org/worksAt', 'src_value': 'http://example.org/Company', 'dst_value': 'http://example.org/CompanyY'}, {'subject': 'urn:uuid:550e8400-e29b-41d4-a716-446655440000', 'property': 'http://example.org/location', 'src_value': None, 'dst_value': 'New York'}]
Comparing test_src.jsonld with test_dst.jsonld.

### Compare KG triples present in a folder

In [10]:
!provsense-cli -- compare --source src --destination dst

2025-02-07 16:14:27,125 - INFO - Comparing directories: src with dst.
2025-02-07 16:14:27,125 - INFO - Processing files: src/test_file.jsonld with dst/test_file.jsonld
2025-02-07 16:14:27,125 - INFO - Checking the input types, i.e, whether it is ttl, json-ld or nt
2025-02-07 16:14:27,130 - INFO - Checking the input types, i.e, whether it is ttl, json-ld or nt
2025-02-07 16:14:27,178 - INFO - Processing files: src/test_file_b.jsonld with dst/test_file_b.jsonld
2025-02-07 16:14:27,178 - INFO - Checking the input types, i.e, whether it is ttl, json-ld or nt
2025-02-07 16:14:27,179 - INFO - Checking the input types, i.e, whether it is ttl, json-ld or nt
{'test_file.jsonld': [{'subject': 'urn:uuid:550e8400-e29b-41d4-a716-446655440000', 'property': 'http://example.org/worksAt', 'src_value': 'http://example.org/CompanyX', 'dst_value': 'http://example.org/CompanyY'}, {'subject': 'urn:uuid:550e8400-e29b-41d4-a716-446655440000', 'property': 'http://example.org/location', 'src_value': None, 'dst_value': 'New York'}], 'test_file_b.jsonld': [{'subject': 'http://dbpedia.org/resource/Albert_Einstein', 'property': 'http://schema.org/sameAs', 'src_value': 'https://www.wikidata.org/wiki/Q937', 'dst_value': 'https://en.wikipedia.org/wiki/Albert_Einstein'}, {'subject': 'http://dbpedia.org/resource/Albert_Einstein', 'property': 'http://schema.org/nationality', 'src_value': 'http://dbpedia.org/resource/Germany', 'dst_value': 'http://dbpedia.org/resource/Switzerland'}, {'subject': 'http://dbpedia.org/resource/Albert_Einstein', 'property': 'http://schema.org/nationality', 'src_value': 'http://dbpedia.org/resource/Germany', 'dst_value': 'http://dbpedia.org/resource/United_States'}, {'subject': 'http://dbpedia.org/resource/Albert_Einstein', 'property': 'http://schema.org/affiliation', 'src_value': 'http://dbpedia.org/resource/University_of_Berlin', 'dst_value': 'http://dbpedia.org/resource/Princeton_University'}, {'subject': 'http://dbpedia.org/resource/Albert_Einstein', 'property': 'http://schema.org/affiliation', 'src_value': 'http://dbpedia.org/resource/University_of_Berlin', 'dst_value': 'http://dbpedia.org/resource/ETH_Zurich'}, {'subject': 'http://dbpedia.org/resource/Albert_Einstein', 'property': 'http://schema.org/nationality', 'src_value': 'http://dbpedia.org/resource/Switzerland', 'dst_value': 'http://dbpedia.org/resource/Germany'}, {'subject': 'http://dbpedia.org/resource/Albert_Einstein', 'property': 'http://schema.org/nationality', 'src_value': 'http://dbpedia.org/resource/Switzerland', 'dst_value': 'http://dbpedia.org/resource/United_States'}, {'subject': 'http://dbpedia.org/resource/Albert_Einstein', 'property': 'http://schema.org/knowsAbout', 'src_value': 'http://dbpedia.org/resource/Brownian_motion', 'dst_value': 'http://dbpedia.org/resource/Quantum_mechanics'}, {'subject': 'http://dbpedia.org/resource/Albert_Einstein', 'property': 'http://schema.org/knowsAbout', 'src_value': 'http://dbpedia.org/resource/Brownian_motion', 'dst_value': 'http://dbpedia.org/resource/Theory_of_relativity'}, {'subject': 'http://dbpedia.org/resource/Albert_Einstein', 'property': 'http://schema.org/knowsAbout', 'src_value': 'http://dbpedia.org/resource/Quantum_mechanics', 'dst_value': 'http://dbpedia.org/resource/Brownian_motion'}, {'subject': 'http://dbpedia.org/resource/Albert_Einstein', 'property': 'http://schema.org/knowsAbout', 'src_value': 'http://dbpedia.org/resource/Quantum_mechanics', 'dst_value': 'http://dbpedia.org/resource/Theory_of_relativity'}, {'subject': 'http://dbpedia.org/resource/Albert_Einstein', 'property': 'http://schema.org/knowsAbout', 'src_value': 'http://dbpedia.org/resource/Theory_of_relativity', 'dst_value': 'http://dbpedia.org/resource/Brownian_motion'}, {'subject': 'http://dbpedia.org/resource/Albert_Einstein', 'property': 'http://schema.org/knowsAbout', 'src_value': 'http://dbpedia.org/resource/Theory_of_relativity', 'dst_value': 'http://dbpedia.org/resource/Quantum_mechanics'}, {'subject': 'http://dbpedia.org/resource/Albert_Einstein', 'property': 'http://schema.org/affiliation', 'src_value': 'http://dbpedia.org/resource/Princeton_University', 'dst_value': 'http://dbpedia.org/resource/University_of_Berlin'}, {'subject': 'http://dbpedia.org/resource/Albert_Einstein', 'property': 'http://schema.org/affiliation', 'src_value': 'http://dbpedia.org/resource/Princeton_University', 'dst_value': 'http://dbpedia.org/resource/ETH_Zurich'}, {'subject': 'http://dbpedia.org/resource/Albert_Einstein', 'property': 'http://schema.org/alternateName', 'src_value': 'Einstein', 'dst_value': 'Prof. Einstein'}, {'subject': 'http://dbpedia.org/resource/Albert_Einstein', 'property': 'http://schema.org/alternateName', 'src_value': 'Prof. Einstein', 'dst_value': 'Einstein'}, {'subject': 'http://dbpedia.org/resource/Albert_Einstein', 'property': 'http://schema.org/nationality', 'src_value': 'http://dbpedia.org/resource/United_States', 'dst_value': 'http://dbpedia.org/resource/Germany'}, {'subject': 'http://dbpedia.org/resource/Albert_Einstein', 'property': 'http://schema.org/nationality', 'src_value': 'http://dbpedia.org/resource/United_States', 'dst_value': 'http://dbpedia.org/resource/Switzerland'}, {'subject': 'http://dbpedia.org/resource/Albert_Einstein', 'property': 'http://schema.org/affiliation', 'src_value': 'http://dbpedia.org/resource/ETH_Zurich', 'dst_value': 'http://dbpedia.org/resource/University_of_Berlin'}, {'subject': 'http://dbpedia.org/resource/Albert_Einstein', 'property': 'http://schema.org/affiliation', 'src_value': 'http://dbpedia.org/resource/ETH_Zurich', 'dst_value': 'http://dbpedia.org/resource/Princeton_University'}, {'subject': 'http://dbpedia.org/resource/Albert_Einstein', 'property': 'http://schema.org/sameAs', 'src_value': 'https://en.wikipedia.org/wiki/Albert_Einstein', 'dst_value': 'https://www.wikidata.org/wiki/Q937'}, {'subject': 'http://dbpedia.org/resource/Brownian_motion', 'property': 'http://schema.org/name', 'src_value': 'Brownian', 'dst_value': 'Brownian Motion'}, {'subject': 'http://dbpedia.org/resource/Theory_of_relativity', 'property': 'http://schema.org/name', 'src_value': 'Relativity', 'dst_value': 'Theory of Relativity'}]}
Comparing src with dst.

## Programmatic Usage

In [11]:
from ProvSense.app import compare_items

In [12]:

#KG string compare
src = """{ "@context": { "ex": "http://example.org/" }, "@id": "ex:Person1", "@type": "ex:Person", "ex:name": "Alice" }"""

dst = """{ "@context": { "ex": "http://example.org/" }, "@id": "ex:Person1", "@type": "ex:Person", "ex:name": "BoB" }"""

pd.DataFrame(compare_items(src,dst))

2025-02-07 16:14:27,355 - INFO - Comparing strings: { "@context": { "ex": "http://example.org/" }, "@id": "ex:Person1", "@type": "ex:Person", "ex:name": "Alice" } with { "@context": { "ex": "http://example.org/" }, "@id": "ex:Person1", "@type": "ex:Person", "ex:name": "BoB" }.
2025-02-07 16:14:27,356 - INFO - Checking the input types, i.e, whether it is ttl, json-ld or nt
2025-02-07 16:14:27,362 - INFO - Checking the input types, i.e, whether it is ttl, json-ld or nt

                      subject                 property src_value dst_value
0  http://example.org/Person1  http://example.org/name     Alice       BoB

In [13]:
#kg file compare
pd.DataFrame(compare_items("test_src.jsonld","test_dst.jsonld"))

2025-02-07 16:14:27,419 - INFO - Comparing files: test_src.jsonld with test_dst.jsonld.
2025-02-07 16:14:27,419 - INFO - Checking the input types, i.e, whether it is ttl, json-ld or nt
2025-02-07 16:14:27,420 - INFO - Checking the input types, i.e, whether it is ttl, json-ld or nt

,subject,property,src_value,dst_value
0,urn:uuid:550e8400-e29b-41d4-a716-446655440000,http://example.org/worksAt,http://example.org/Company,http://example.org/CompanyY
1,urn:uuid:550e8400-e29b-41d4-a716-446655440000,http://example.org/location,None,New York

In [14]:
#kg directory compare
compare_items("src","dst")

2025-02-07 16:14:27,449 - INFO - Comparing directories: src with dst.
2025-02-07 16:14:27,451 - INFO - Processing files: src/test_file_b.jsonld with dst/test_file_b.jsonld
2025-02-07 16:14:27,453 - INFO - Checking the input types, i.e, whether it is ttl, json-ld or nt
2025-02-07 16:14:27,456 - INFO - Checking the input types, i.e, whether it is ttl, json-ld or nt
2025-02-07 16:14:27,496 - INFO - Processing files: src/test_file.jsonld with dst/test_file.jsonld
2025-02-07 16:14:27,497 - INFO - Checking the input types, i.e, whether it is ttl, json-ld or nt
2025-02-07 16:14:27,498 - INFO - Checking the input types, i.e, whether it is ttl, json-ld or nt

{'test_file_b.jsonld': [{'subject': 'http://dbpedia.org/resource/Albert_Einstein',
   'property': 'http://schema.org/alternateName',
   'src_value': 'Prof. Einstein',
   'dst_value': 'Einstein'},
  {'subject': 'http://dbpedia.org/resource/Albert_Einstein',
   'property': 'http://schema.org/sameAs',
   'src_value': 'https://www.wikidata.org/wiki/Q937',
   'dst_value': 'https://en.wikipedia.org/wiki/Albert_Einstein'},
  {'subject': 'http://dbpedia.org/resource/Albert_Einstein',
   'property': 'http://schema.org/alternateName',
   'src_value': 'Einstein',
   'dst_value': 'Prof. Einstein'},
  {'subject': 'http://dbpedia.org/resource/Albert_Einstein',
   'property': 'http://schema.org/sameAs',
   'src_value': 'https://en.wikipedia.org/wiki/Albert_Einstein',
   'dst_value': 'https://www.wikidata.org/wiki/Q937'},
  {'subject': 'http://dbpedia.org/resource/Albert_Einstein',
   'property': 'http://schema.org/nationality',
   'src_value': 'http://dbpedia.org/resource/United_States',
   'dst_value': 'http://dbpedia.org/resource/Germany'},
  {'subject': 'http://dbpedia.org/resource/Albert_Einstein',
   'property': 'http://schema.org/nationality',
   'src_value': 'http://dbpedia.org/resource/United_States',
   'dst_value': 'http://dbpedia.org/resource/Switzerland'},
  {'subject': 'http://dbpedia.org/resource/Albert_Einstein',
   'property': 'http://schema.org/knowsAbout',
   'src_value': 'http://dbpedia.org/resource/Theory_of_relativity',
   'dst_value': 'http://dbpedia.org/resource/Brownian_motion'},
  {'subject': 'http://dbpedia.org/resource/Albert_Einstein',
   'property': 'http://schema.org/knowsAbout',
   'src_value': 'http://dbpedia.org/resource/Theory_of_relativity',
   'dst_value': 'http://dbpedia.org/resource/Quantum_mechanics'},
  {'subject': 'http://dbpedia.org/resource/Albert_Einstein',
   'property': 'http://schema.org/knowsAbout',
   'src_value': 'http://dbpedia.org/resource/Brownian_motion',
   'dst_value': 'http://dbpedia.org/resource/Theory_of_relativity'},
  {'subject': 'http://dbpedia.org/resource/Albert_Einstein',
   'property': 'http://schema.org/knowsAbout',
   'src_value': 'http://dbpedia.org/resource/Brownian_motion',
   'dst_value': 'http://dbpedia.org/resource/Quantum_mechanics'},
  {'subject': 'http://dbpedia.org/resource/Albert_Einstein',
   'property': 'http://schema.org/affiliation',
   'src_value': 'http://dbpedia.org/resource/University_of_Berlin',
   'dst_value': 'http://dbpedia.org/resource/Princeton_University'},
  {'subject': 'http://dbpedia.org/resource/Albert_Einstein',
   'property': 'http://schema.org/affiliation',
   'src_value': 'http://dbpedia.org/resource/University_of_Berlin',
   'dst_value': 'http://dbpedia.org/resource/ETH_Zurich'},
  {'subject': 'http://dbpedia.org/resource/Albert_Einstein',
   'property': 'http://schema.org/nationality',
   'src_value': 'http://dbpedia.org/resource/Germany',
   'dst_value': 'http://dbpedia.org/resource/United_States'},
  {'subject': 'http://dbpedia.org/resource/Albert_Einstein',
   'property': 'http://schema.org/nationality',
   'src_value': 'http://dbpedia.org/resource/Germany',
   'dst_value': 'http://dbpedia.org/resource/Switzerland'},
  {'subject': 'http://dbpedia.org/resource/Albert_Einstein',
   'property': 'http://schema.org/knowsAbout',
   'src_value': 'http://dbpedia.org/resource/Quantum_mechanics',
   'dst_value': 'http://dbpedia.org/resource/Theory_of_relativity'},
  {'subject': 'http://dbpedia.org/resource/Albert_Einstein',
   'property': 'http://schema.org/knowsAbout',
   'src_value': 'http://dbpedia.org/resource/Quantum_mechanics',
   'dst_value': 'http://dbpedia.org/resource/Brownian_motion'},
  {'subject': 'http://dbpedia.org/resource/Albert_Einstein',
   'property': 'http://schema.org/affiliation',
   'src_value': 'http://dbpedia.org/resource/Princeton_University',
   'dst_value': 'http://dbpedia.org/resource/University_of_Berlin'},
  {'subject': 'http://dbpedia.org/resource/Albert_Einstein',
   'property': 'http://schema.org/affiliation',
   'src_value': 'http://dbpedia.org/resource/Princeton_University',
   'dst_value': 'http://dbpedia.org/resource/ETH_Zurich'},
  {'subject': 'http://dbpedia.org/resource/Albert_Einstein',
   'property': 'http://schema.org/affiliation',
   'src_value': 'http://dbpedia.org/resource/ETH_Zurich',
   'dst_value': 'http://dbpedia.org/resource/University_of_Berlin'},
  {'subject': 'http://dbpedia.org/resource/Albert_Einstein',
   'property': 'http://schema.org/affiliation',
   'src_value': 'http://dbpedia.org/resource/ETH_Zurich',
   'dst_value': 'http://dbpedia.org/resource/Princeton_University'},
  {'subject': 'http://dbpedia.org/resource/Albert_Einstein',
   'property': 'http://schema.org/nationality',
   'src_value': 'http://dbpedia.org/resource/Switzerland',
   'dst_value': 'http://dbpedia.org/resource/United_States'},
  {'subject': 'http://dbpedia.org/resource/Albert_Einstein',
   'property': 'http://schema.org/nationality',
   'src_value': 'http://dbpedia.org/resource/Switzerland',
   'dst_value': 'http://dbpedia.org/resource/Germany'},
  {'subject': 'http://dbpedia.org/resource/Brownian_motion',
   'property': 'http://schema.org/name',
   'src_value': 'Brownian',
   'dst_value': 'Brownian Motion'},
  {'subject': 'http://dbpedia.org/resource/Theory_of_relativity',
   'property': 'http://schema.org/name',
   'src_value': 'Relativity',
   'dst_value': 'Theory of Relativity'}],
 'test_file.jsonld': [{'subject': 'urn:uuid:550e8400-e29b-41d4-a716-446655440000',
   'property': 'http://example.org/worksAt',
   'src_value': 'http://example.org/CompanyX',
   'dst_value': 'http://example.org/CompanyY'},
  {'subject': 'urn:uuid:550e8400-e29b-41d4-a716-446655440000',
   'property': 'http://example.org/location',
   'src_value': None,
   'dst_value': 'New York'}]}